<?php
namespace app\modules\admin\controllers;

use app\modules\admin\controllers\common\BaseController;

class IndexController extends BaseController {

    public function beforeAction($action)
    {

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionIndex(){
        var_dump("das");
        return;
    }
}