<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/10/2 0002
 * Time: 8:57
 */

namespace app\modules\admin\controllers\common;


use app\common\components\BasePublicController;

class BaseController extends BasePublicController
{
    public $no_use_login = [
        'default/index',
        'default/'
    ];

    public function beforeAction($action)
    {
        $this->layout = false;
        var_dump("aa");
        var_dump("方法:".$action->id);
        var_dump("控制器".$action->controller->id);
        var_dump($action);
        return true;
     //   return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}