<?php
namespace app\common\components;

use yii\base\Widget;

class CategoryWidget extends Widget{

    public function run()
    {
        $this->render('category',['mdoel'=>1]);
//        parent::run(); // TODO: Change the autogenerated stub
    }
}