<?php
namespace app\assets;

use yii\web\AssetBundle;

class AdminAsset extends AssetBundle{
    public $basePath = '@webroot';
    public $baseUrl = '@web';

    public function registerAssetFiles($view)
    {
        $this->css = [
            'admin/css/bootstrap.min.css',
            'font-awesome/css/font-awesome.css',
            'admin/css/dermadefault.css',
            'admin/ss/templatecss.css',
            'admin/css/style.css'
        ];

        $this->js = [
            'Admin/js/jquery-1.10.2.js',
            'Admin/js/bootstrap.min.js',
            'Admin/js/global.js',
            'Admin/js/layer/layer.js'
        ];
        parent::registerAssetFiles($view); // TODO: Change the autogenerated stub
    }


}